# Generated by Django 3.2 on 2024-12-19 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_cliente_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')]),
        ),
    ]
