# Generated by Django 3.2 on 2024-12-19 22:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_trabajador_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator(message='Debe ingresar un correo válido.')]),
        ),
    ]
