# Generated by Django 3.2 on 2024-12-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_cliente_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='fecha_ingreso',
            field=models.DateTimeField(),
        ),
    ]
